"""empty message

Revision ID: 4a4747217e57
Revises: 881f7571b0cb
Create Date: 2021-08-27 14:45:42.313163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a4747217e57'
down_revision = '881f7571b0cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('gender', table_name='People')
    op.drop_index('hair_color', table_name='People')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('hair_color', 'People', ['hair_color'], unique=False)
    op.create_index('gender', 'People', ['gender'], unique=False)
    # ### end Alembic commands ###
